### Recommendation System Notebook Capstone
Recommendation System Notebook
- User based recommendation
- User based prediction & evaluation
- Item based recommendation
- Item based prediction & evaluation





Different Approaches to develop Recommendation System -

- Demographich based Recommendation System

- Content Based Recommendation System

- Collaborative filtering Recommendation System

### Step1: Exploratory data analysis 
#### 1.1 Importing Libraries

In [156]:
# import libraties
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics.pairwise import pairwise_distances

In [157]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### 1.2 Loading Data

In [158]:
#df = pd.read_csv("C:/Users/Admin/Downloads/datacapstone/sample30.csv")
df = pd.read_csv("/content/drive/MyDrive/sample30.csv")
print(df.shape)
df.head(3)

(30000, 15)


id            brand  ... reviews_username user_sentiment
0  AV13O1A8GV-KLJ3akUyj  Universal Music  ...           joshua       Positive
1  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
2  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive

[3 rows x 15 columns]

#### 1.3 Checking for Duplicates

In [159]:
# Checking duplicate count
duplicates=df[df.duplicated(['reviews_username','id'])]
print(duplicates.shape)
duplicates.head(3)

(2395, 15)


id      brand  ... reviews_username user_sentiment
2   AV14LG0R-jtxr-f38QfS   Lundberg  ...        dorothy w       Positive
12  AV16khLE-jtxr-f38VFn        K-Y  ...          jds1992       Negative
44  AV1h6Gu0glJLPUi8IjA_  Johnson's  ...             solo       Positive

[3 rows x 15 columns]

#### 1.4 Checking Data Info

In [160]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   id                    30000 non-null  object
 1   brand                 30000 non-null  object
 2   categories            30000 non-null  object
 3   manufacturer          29859 non-null  object
 4   name                  30000 non-null  object
 5   reviews_date          29954 non-null  object
 6   reviews_didPurchase   15932 non-null  object
 7   reviews_doRecommend   27430 non-null  object
 8   reviews_rating        30000 non-null  int64 
 9   reviews_text          30000 non-null  object
 10  reviews_title         29810 non-null  object
 11  reviews_userCity      1929 non-null   object
 12  reviews_userProvince  170 non-null    object
 13  reviews_username      29937 non-null  object
 14  user_sentiment        29999 non-null  object
dtypes: int64(1), object(14)
memory usage

#### 1.5 Removing Duplicates

In [161]:
# Removing all the duplicate values with combination of product id and username
df.drop_duplicates(subset=['id','reviews_username'], keep='first', inplace=True)
print(df.shape)
df.head(3)

(27605, 15)


id            brand  ... reviews_username user_sentiment
0  AV13O1A8GV-KLJ3akUyj  Universal Music  ...           joshua       Positive
1  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
3  AV16khLE-jtxr-f38VFn              K-Y  ...          rebecca       Negative

[3 rows x 15 columns]

#### 1.6 Downloading Main pickle file

In [291]:
dfMain = df[['id', 'reviews_username', 'reviews_rating']]
print(dfMain.shape)
dfMain.to_pickle("MainData.pkl")
dfMain.head()

(27605, 3)


id reviews_username  reviews_rating
0  AV13O1A8GV-KLJ3akUyj           joshua               5
1  AV14LG0R-jtxr-f38QfS        dorothy w               5
3  AV16khLE-jtxr-f38VFn          rebecca               1
4  AV16khLE-jtxr-f38VFn        walker557               1
5  AV16khLE-jtxr-f38VFn         samantha               1

#### 1.7 Checking Null Values

In [163]:
dfMain.isna().sum()

id                   0
reviews_username    17
reviews_rating       0
dtype: int64

#### 1.8 Removing null usernames

In [164]:
dfMain = dfMain[~dfMain.reviews_username.isna()]
print("My data's shape is:", dfMain.shape)
dfMain.head(10)

My data's shape is: (27588, 3)


id reviews_username  reviews_rating
0   AV13O1A8GV-KLJ3akUyj           joshua               5
1   AV14LG0R-jtxr-f38QfS        dorothy w               5
3   AV16khLE-jtxr-f38VFn          rebecca               1
4   AV16khLE-jtxr-f38VFn        walker557               1
5   AV16khLE-jtxr-f38VFn         samantha               1
6   AV16khLE-jtxr-f38VFn          raeanne               1
7   AV16khLE-jtxr-f38VFn           kimmie               1
8   AV16khLE-jtxr-f38VFn           cassie               1
9   AV16khLE-jtxr-f38VFn         moore222               1
10  AV16khLE-jtxr-f38VFn          jds1992               1

In [165]:
# Checking unique count
print(dfMain.nunique())

id                    271
reviews_username    24914
reviews_rating          5
dtype: int64


In [166]:
Checking duplication in id and username combination
dfMain.duplicated(['reviews_username','id'])


0        False
1        False
3        False
4        False
5        False
         ...  
29995    False
29996    False
29997    False
29998    False
29999    False
Length: 27588, dtype: bool

In [167]:
# Removing the duplicates
dup=dfMain[dfMain.duplicated(['reviews_username','id'])]
dup

Empty DataFrame
Columns: [id, reviews_username, reviews_rating]
Index: []

#### 1.9 Dividing the dataset into train and test

In [168]:
# Test and Train split of the dataset.
from sklearn.model_selection import train_test_split
train, test = train_test_split(dfMain, test_size=0.30, random_state=31)

In [169]:
# Printing Shapes
print(train.shape)
print(test.shape)


(19311, 3)
(8277, 3)


In [170]:
# Pivot the train rating with username and id.
df_pivot = train.pivot(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
).fillna(0)

In [171]:
# Print the data
df_pivot.head(5)

id                AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
reviews_username                        ...                      
00dog3                             0.0  ...                   0.0
00sab00                            0.0  ...                   0.0
01impala                           0.0  ...                   0.0
02dakota                           0.0  ...                   0.0
02deuce                            0.0  ...                   0.0

[5 rows x 255 columns]

In [172]:
# Checking Shape of table
df_pivot.shape

(17891, 255)

#### 1.10 Creating dummy train & dummy test dataset

In [174]:
# Copy the train dataset into dummy_train
dummy_train = train.copy()

In [175]:
dummy_train.head()

id reviews_username  reviews_rating
25816  AVpfPaoqLJeJML435Xk9            jlcii               5
21510  AVpfm8yiLJeJML43AYyu           susanb               1
4444   AVpe9W4D1cnluZ0-avf0       cbenn93308               5
10332  AVpf3VOfilAPnD_xjpun     savvysaver25               5
13321  AVpf3VOfilAPnD_xjpun            rocsi               5

In [176]:
# The movies not rated by user is marked as 1 for prediction. 
dummy_train['reviews_rating'] = dummy_train['reviews_rating'].apply(lambda x: 0 if x>=1 else 1)

In [177]:
# Convert the dummy train dataset into matrix format.
dummy_train = dummy_train.pivot(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
).fillna(1)


In [178]:
dummy_train.head()

id                AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
reviews_username                        ...                      
00dog3                             1.0  ...                   1.0
00sab00                            1.0  ...                   1.0
01impala                           1.0  ...                   1.0
02dakota                           1.0  ...                   1.0
02deuce                            1.0  ...                   1.0

[5 rows x 255 columns]

Cosine Similarity

Cosine Similarity is a measurement that quantifies the similarity between two vectors [Which is Rating Vector in this case]

Adjusted Cosine

Adjusted cosine similarity is a modified version of vector-based similarity where we incorporate the fact that different users have different ratings schemes. In other words, some users might rate items highly in general, and others might give items lower ratings as a preference. To handle this nature from rating given by user , we subtract average ratings for each user from each user's rating for different movies.

In [179]:
df_pivot.index.nunique()

17891

In [180]:

# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_pivot, metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 1.]]


In [181]:
user_correlation.shape

(17891, 17891)

In [182]:
#### Using adjusted Cosine

In [183]:
### Here, we are not removing the NaN values and calculating the mean only for the movies rated by the user

In [184]:
# Create a user-product matrix.
df_pivot = train.pivot(
     index='reviews_username',
    columns='id',
    values='reviews_rating'
)

In [185]:
df_pivot.head()

id                AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
reviews_username                        ...                      
00dog3                             NaN  ...                   NaN
00sab00                            NaN  ...                   NaN
01impala                           NaN  ...                   NaN
02dakota                           NaN  ...                   NaN
02deuce                            NaN  ...                   NaN

[5 rows x 255 columns]

In [186]:
df_pivot.shape

(17891, 255)

In [187]:
### Normalising the rating of the movie for each user around 0 mean


In [188]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [189]:
df_subtracted.head()

id                AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
reviews_username                        ...                      
00dog3                             NaN  ...                   NaN
00sab00                            NaN  ...                   NaN
01impala                           NaN  ...                   NaN
02dakota                           NaN  ...                   NaN
02deuce                            NaN  ...                   NaN

[5 rows x 255 columns]

In [191]:
# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [192]:
user_correlation.shape

(17891, 17891)

### Prediction - User User

In [193]:
# Doing the prediction for the users which are positively related with other users, and not the users which are negatively related as we are interested in the users which are more similar to the current users. So, ignoring the correlation for values less than 0.

In [194]:
user_correlation[user_correlation<0]=0
user_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [195]:
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [196]:
user_predicted_ratings.shape

(17891, 255)

In [197]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

id                AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
reviews_username                        ...                      
00dog3                             0.0  ...                   0.0
00sab00                            0.0  ...                   0.0
01impala                           0.0  ...                   0.0
02dakota                           0.0  ...                   0.0
02deuce                            0.0  ...                   0.0

[5 rows x 255 columns]

In [198]:
### finding top 5 recommendation for the user

In [199]:
# Take the user ID as input.
user_input = (input("Enter your user name"))
print(user_input)

Enter your user name02deuce
02deuce


In [200]:
user_final_rating.head(3)

id                AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
reviews_username                        ...                      
00dog3                             0.0  ...                   0.0
00sab00                            0.0  ...                   0.0
01impala                           0.0  ...                   0.0

[3 rows x 255 columns]

In [201]:
d = user_final_rating.loc[user_input].sort_values(ascending=False)[0:5]
d

id
AVpfvieo1cnluZ0-qdnu    0.0
AVpf-lMV1cnluZ0-ub0_    0.0
AVpf4WWN1cnluZ0-s7Wj    0.0
AVpf3okQLJeJML43FMif    0.0
AVpf3VOfilAPnD_xjpun    0.0
Name: 02deuce, dtype: float64

In [205]:

### Evaluation - User User

In [206]:
#Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the product already rated by the user insead of predicting it for the product not rated by the user

In [207]:
# Find out the common users of test and train dataset.
common = test[test.reviews_username.isin(train.reviews_username)]
common.shape

(1106, 3)

In [208]:
common.head()

id reviews_username  reviews_rating
4245   AVpe9W4D1cnluZ0-avf0           teresa               5
19882  AVpfJP1C1cnluZ0-e3Xy            shaba               5
26308  AVpfPnrU1cnluZ0-g9rL           jayjay               4
6284   AVpf385g1cnluZ0-s0_t             meme               3
15580  AVpf5ujMilAPnD_xkQVi             nana               5

In [209]:
# convert into the user-product matrix.
common_user_based_matrix = common.pivot_table(index='reviews_username', columns='id', values='reviews_rating')


In [210]:
print(common_user_based_matrix.shape)
common_user_based_matrix.head()

(925, 126)


id                AV16khLE-jtxr-f38VFn  ...  AVpfv4TlilAPnD_xhjNS
reviews_username                        ...                      
00sab00                            NaN  ...                   NaN
1234                               NaN  ...                   NaN
1943                               NaN  ...                   NaN
37f5p                              NaN  ...                   NaN
50cal                              NaN  ...                   NaN

[5 rows x 126 columns]

In [211]:
# Convert the user_correlation matrix into dataframe.
user_correlation_df = pd.DataFrame(user_correlation)

In [212]:
user_correlation_df.head()

0      1      2      3      4      ...  17886  17887  17888  17889  17890
0    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
1    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
2    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
3    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
4    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0

[5 rows x 17891 columns]

In [213]:
df_subtracted.head(1)

id                AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
reviews_username                        ...                      
00dog3                             NaN  ...                   NaN

[1 rows x 255 columns]

In [214]:
user_correlation_df['username'] = df_subtracted.index
user_correlation_df.set_index('username',inplace=True)
user_correlation_df.head()

0      1      2      3      4      ...  17886  17887  17888  17889  17890
username                                     ...                                   
00dog3      0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
00sab00     0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
01impala    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
02dakota    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
02deuce     0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0

[5 rows x 17891 columns]

In [217]:
print(common.shape)
common.head(1)

(1106, 3)


id reviews_username  reviews_rating
4245  AVpe9W4D1cnluZ0-avf0           teresa               5

In [218]:
list_name = common.reviews_username.tolist()

user_correlation_df.columns = df_subtracted.index.tolist()

user_correlation_df_1 =  user_correlation_df[user_correlation_df.index.isin(list_name)]

In [219]:
user_correlation_df_1.shape

(925, 17891)

In [220]:
user_correlation_df_2 = user_correlation_df_1.T[user_correlation_df_1.T.index.isin(list_name)]

In [221]:
user_correlation_df_3 = user_correlation_df_2.T

In [222]:
print(user_correlation_df_3.shape)
user_correlation_df_3.head()

(925, 925)


00sab00  1234  1943  37f5p  50cal  ...  xmom  yeyo  yummy  zippy  zitro
username                                     ...                                 
00sab00       0.0   0.0   0.0    0.0    0.0  ...   0.0   0.0    0.0    0.0    0.0
1234          0.0   0.0   0.0    0.0    0.0  ...   0.0   0.0    0.0    0.0    0.0
1943          0.0   0.0   0.0    0.0    0.0  ...   0.0   0.0    0.0    0.0    0.0
37f5p         0.0   0.0   0.0    0.0    0.0  ...   0.0   0.0    0.0    0.0    0.0
50cal         0.0   0.0   0.0    0.0    0.0  ...   0.0   0.0    0.0    0.0    0.0

[5 rows x 925 columns]

In [223]:
user_correlation_df_3[user_correlation_df_3<0]=0

common_user_predicted_ratings = np.dot(user_correlation_df_3, common_user_based_matrix.fillna(0))
common_user_predicted_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [224]:
#working on ddummy test data

In [225]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='id', values='reviews_rating').fillna(0)

In [226]:
dummy_test.shape

(925, 126)

In [227]:
common_user_based_matrix.head()

id                AV16khLE-jtxr-f38VFn  ...  AVpfv4TlilAPnD_xhjNS
reviews_username                        ...                      
00sab00                            NaN  ...                   NaN
1234                               NaN  ...                   NaN
1943                               NaN  ...                   NaN
37f5p                              NaN  ...                   NaN
50cal                              NaN  ...                   NaN

[5 rows x 126 columns]

In [228]:
dummy_test.head(2)

id                AV16khLE-jtxr-f38VFn  ...  AVpfv4TlilAPnD_xhjNS
reviews_username                        ...                      
00sab00                            0.0  ...                   0.0
1234                               0.0  ...                   0.0

[2 rows x 126 columns]

In [229]:
common_user_predicted_ratings = np.multiply(common_user_predicted_ratings,dummy_test)

In [230]:
common_user_predicted_ratings.head()

id                AV16khLE-jtxr-f38VFn  ...  AVpfv4TlilAPnD_xhjNS
reviews_username                        ...                      
00sab00                            0.0  ...                   0.0
1234                               0.0  ...                   0.0
1943                               0.0  ...                   0.0
37f5p                              0.0  ...                   0.0
50cal                              0.0  ...                   0.0

[5 rows x 126 columns]

In [231]:
#Calculating the RMSE for only the movies rated by user. For RMSE, normalising the rating to (1,5) range.

In [232]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_user_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(copy=True, feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:375: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:376: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [233]:
common_ = common.pivot_table(index='reviews_username', columns='id', values='reviews_rating')

In [234]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [235]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

2.542261859029648


In [236]:
## Using Item similarity

Item Based Similarity

In [237]:
#Taking the transpose of the rating matrix to normalize the rating around the mean for different movie ID. In the user based similarity, we had taken mean for each user instead of each movie.

In [238]:
df_pivot = train.pivot(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
).T

df_pivot.head()

reviews_username      00dog3  00sab00  01impala  ...  zxjki  zzdiane  zzz1127
id                                               ...                         
AV13O1A8GV-KLJ3akUyj     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV14LG0R-jtxr-f38QfS     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV16khLE-jtxr-f38VFn     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV1YGDqsGV-KLJ3adc-O     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV1YIch7GV-KLJ3addeG     NaN      NaN       NaN  ...    NaN      NaN      NaN

[5 rows x 17891 columns]

In [239]:
#Normalising the movie rating for each movie for using the Adujsted Cosine

In [240]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [241]:
df_subtracted.head(2)

reviews_username      00dog3  00sab00  01impala  ...  zxjki  zzdiane  zzz1127
id                                               ...                         
AV13O1A8GV-KLJ3akUyj     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV14LG0R-jtxr-f38QfS     NaN      NaN       NaN  ...    NaN      NaN      NaN

[2 rows x 17891 columns]

### Finding the cosine similarity using pairwise distances approach

In [242]:
# Item Similarity Matrix
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [243]:
#Filtering the correlation only for which the value is greater than 0. (Positively correlated)

In [244]:
item_correlation[item_correlation<0]=0
item_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [245]:
item_correlation.shape

(255, 255)

In [246]:
##Filtering the correlation only for which the value is greater than 0. (Positively correlated)

In [247]:
item_correlation[item_correlation<0]=0
item_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# Prediction - Item Item

In [248]:
item_predicted_ratings = np.dot((df_pivot.fillna(0).T),item_correlation)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00278407],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00556815]])

In [249]:
item_predicted_ratings.shape

(17891, 255)

In [250]:
dummy_train.shape

(17891, 255)

In [251]:
### Filtering the rating only for the movies not rated by the user for recommendation

In [252]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head(100)

id                AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
reviews_username                        ...                      
00dog3                             0.0  ...               0.00000
00sab00                            0.0  ...               0.00000
01impala                           0.0  ...               0.00000
02dakota                           0.0  ...               0.00000
02deuce                            0.0  ...               0.00000
...                                ...  ...                   ...
2dobies                            0.0  ...               0.00000
2esinapod                          0.0  ...               0.00696
2forhokies                         0.0  ...               0.00000
2iceskates                         0.0  ...               0.00000
2low4zero                          0.0  ...               0.00000

[100 rows x 255 columns]

### Finding the top 5 recommendation for the *user*


In [253]:
# Take the user name as input
user_input = input("Enter your user name")
print(user_input)

Enter your user name01impala
01impala


In [254]:
# Recommending the Top 5 products to the user.
d = item_final_rating.loc[user_input].sort_values(ascending=False)[0:5]
d

id
AVpf5olc1cnluZ0-tPrO    0.147037
AVpfQtEm1cnluZ0-hUpe    0.070275
AVpe41TqilAPnD_xQH3d    0.070205
AVpf0thK1cnluZ0-r8vR    0.045075
AVpfRTh1ilAPnD_xYic2    0.033193
Name: 01impala, dtype: float64

### Evaluation - Item Item

In [255]:
#Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the proudctname already rated by the user insead of predicting it for the productname not rated by the user.

In [256]:
print(test.shape)
print(train.shape)
test.columns

(8277, 3)
(19311, 3)


Index(['id', 'reviews_username', 'reviews_rating'], dtype='object')

In [257]:
common =  test[test.id.isin(train.id)]
common.shape

(8253, 3)

In [258]:
common.head(4)

id reviews_username  reviews_rating
22245  AVpfOIrkilAPnD_xXgDG    albertacanada               4
23511  AVpfPaoqLJeJML435Xk9           reeree               4
7965   AVpf3VOfilAPnD_xjpun          adash75               5
4245   AVpe9W4D1cnluZ0-avf0           teresa               5

In [259]:
common_item_based_matrix = common.pivot_table(index='reviews_username', columns='id', values='reviews_rating').T

In [260]:
common_item_based_matrix.shape

(196, 7926)

In [261]:
common_item_based_matrix.head(4)


reviews_username      00sab00  10ten  ...  zuttle  zyiah4
id                                    ...                
AV16khLE-jtxr-f38VFn      NaN    NaN  ...     NaN     NaN
AV1YGDqsGV-KLJ3adc-O      NaN    NaN  ...     NaN     NaN
AV1YlENIglJLPUi8IHsX      NaN    NaN  ...     NaN     NaN
AV1YmBrdGV-KLJ3adewb      NaN    NaN  ...     NaN     NaN

[4 rows x 7926 columns]

In [262]:
item_correlation_df = pd.DataFrame(item_correlation)

In [263]:
item_correlation_df.head(1)

0    1    2    3    4    5    6    ...  248  249  250  251  252  253  254
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[1 rows x 255 columns]

In [264]:
item_correlation_df['ProudctName'] = df_subtracted.index
item_correlation_df.set_index('ProudctName',inplace=True)


In [265]:
print(item_correlation_df.shape)
item_correlation_df.head(2)

(255, 255)


0    1    2    3    4    ...  250  251  252  253  254
ProudctName                                    ...                         
AV13O1A8GV-KLJ3akUyj  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0
AV14LG0R-jtxr-f38QfS  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0

[2 rows x 255 columns]

In [266]:
list_name = common.id.tolist()

In [267]:
item_correlation_df.columns = df_subtracted.index.tolist()

item_correlation_df_1 =  item_correlation_df[item_correlation_df.index.isin(list_name)]

In [268]:
item_correlation_df_2 = item_correlation_df_1.T[item_correlation_df_1.T.index.isin(list_name)]

item_correlation_df_3 = item_correlation_df_2.T

In [269]:
print(item_correlation_df_3.shape)
item_correlation_df_3.head(2)

(196, 196)


AV16khLE-jtxr-f38VFn  ...  AVpfvieo1cnluZ0-qdnu
ProudctName                                 ...                      
AV16khLE-jtxr-f38VFn                   1.0  ...                   0.0
AV1YGDqsGV-KLJ3adc-O                   0.0  ...                   0.0

[2 rows x 196 columns]

In [270]:
item_correlation_df_3[item_correlation_df_3<0]=0

common_item_predicted_ratings = np.dot(item_correlation_df_3, common_item_based_matrix.fillna(0))
common_item_predicted_ratings


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.00660728, 0.        ,
        0.00032046],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.00408443, 0.        ,
        0.00138298],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00696018]])

In [271]:
common_item_predicted_ratings.shape

(196, 7926)

In [272]:
dummy_test = common.copy()

dummy_test['reviews_rating'] = dummy_test['reviews_rating'].apply(lambda x: 1 if x>=1 else 0)

dummy_test = dummy_test.pivot_table(index='reviews_username', columns='id', values='reviews_rating').T.fillna(0)

common_item_predicted_ratings = np.multiply(common_item_predicted_ratings,dummy_test)

In [273]:
#The products not rated is marked as 0 for evaluation. And make the item- item matrix representaion.

In [274]:
common_item_predicted_ratings.head(2)

reviews_username      00sab00  10ten  ...  zuttle  zyiah4
id                                    ...                
AV16khLE-jtxr-f38VFn      0.0    0.0  ...     0.0     0.0
AV1YGDqsGV-KLJ3adc-O      0.0    0.0  ...     0.0     0.0

[2 rows x 7926 columns]

In [275]:
common_ = common.pivot(index='reviews_username', columns='id', values='reviews_rating').T

In [276]:
common_.head(2)

reviews_username      00sab00  10ten  ...  zuttle  zyiah4
id                                    ...                
AV16khLE-jtxr-f38VFn      NaN    NaN  ...     NaN     NaN
AV1YGDqsGV-KLJ3adc-O      NaN    NaN  ...     NaN     NaN

[2 rows x 7926 columns]

In [277]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_item_predicted_ratings.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(copy=True, feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:375: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:376: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [278]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

In [279]:
rmse = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse)

3.5707446684659967


## Observation: 
#### The RMSE for user based recommendation system is lesser. So we are selecting the same.

In [281]:
dfMain

id reviews_username  reviews_rating
0      AV13O1A8GV-KLJ3akUyj           joshua               5
1      AV14LG0R-jtxr-f38QfS        dorothy w               5
3      AV16khLE-jtxr-f38VFn          rebecca               1
4      AV16khLE-jtxr-f38VFn        walker557               1
5      AV16khLE-jtxr-f38VFn         samantha               1
...                     ...              ...             ...
29995  AVpfW8y_LJeJML437ySW       laurasnchz               5
29996  AVpfW8y_LJeJML437ySW    scarlepadilla               5
29997  AVpfW8y_LJeJML437ySW       liviasuexo               5
29998  AVpfW8y_LJeJML437ySW         ktreed95               5
29999  AVpfW8y_LJeJML437ySW        kcoopxoxo               5

[27588 rows x 3 columns]

In [282]:

# Take the user ID as input
user_input = str(input("Enter your user name"))
print(user_input)

Enter your user name01impala
01impala


In [287]:

recommendations = user_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
mapping= df[['id','name']]
mapping = pd.DataFrame.drop_duplicates(mapping)
recommendations = pd.merge(recommendations,mapping, left_on='id', right_on='id', how = 'left')
recommendations

id  ...                                               name
0   AVpfvieo1cnluZ0-qdnu  ...  L'oreal Paris Advanced Hairstyle TXT IT Hyper-...
1   AVpf-lMV1cnluZ0-ub0_  ...                             If A Man Answers (dvd)
2   AVpf4WWN1cnluZ0-s7Wj  ...                 Chips Deluxe Soft 'n Chewy Cookies
3   AVpf3okQLJeJML43FMif  ...                       Tai Pei Sweet & Sour Chicken
4   AVpf3VOfilAPnD_xjpun  ...  Clorox Disinfecting Wipes Value Pack Scented 1...
5   AVpf385g1cnluZ0-s0_t  ...                             Hormel Chili, No Beans
6   AVpf2tw1ilAPnD_xjflC  ...                   Red (special Edition) (dvdvideo)
7   AVpf1ryk1cnluZ0-sONd  ...  Germ Guardian174 Elite 3-In-1 Pet Pure True He...
8   AVpf1pwXLJeJML43EqpT  ...                      Colorganics Lipstick, Cayenne
9   AVpf0thK1cnluZ0-r8vR  ...                100:Complete First Season (blu-Ray)
10  AVpf0pfrilAPnD_xi6s_  ...    Nearly Natural 5.5' Bamboo W/decorative Planter
11  AVpf0kZFilAPnD_xi5QZ  ...  Annie's Homegrown Gluten Free Double Chocolate...
12  AVpf0eb2LJeJML43EVSt  ...     The Resident Evil Collection 5 Discs (blu-Ray)
13  AVpf0YhQLJeJML43ETff  ...         Australian Gold Exotic Blend Lotion, SPF 4
14  AVpf0O60ilAPnD_xizE6  ...  Super Poligrip Denture Adhesive Cream, Ultra F...
15  AVpf-k78LJeJML43G4qN  ...  Metzeler ME888 Marathon Ultra Custom Touring F...
16  AVpf5CnILJeJML43FjaU  ...  WeatherTech 40647 14-15 Outlander Cargo Liners...
17  AVpf-bS61cnluZ0-uZcq  ...  Nature's Path Chunky Chocolate Peanut Chewy Gr...
18  AVpf-GsfLJeJML43GxG4  ...  Gain Original Scent Liquid Fabric Softener 129 Oz
19  AVpf--o9LJeJML43G_Fq  ...  Vaseline Intensive Care Healthy Hands Stronger...

[20 rows x 3 columns]

#### Exporting the Final Rating pickle file

In [288]:
user_final_rating.to_pickle("user_final_rating.pkl")
pickled_user_final_rating = pd.read_pickle("user_final_rating.pkl")
pickled_user_final_rating

id                AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
reviews_username                        ...                      
00dog3                             0.0  ...                   0.0
00sab00                            0.0  ...                   0.0
01impala                           0.0  ...                   0.0
02dakota                           0.0  ...                   0.0
02deuce                            0.0  ...                   0.0
...                                ...  ...                   ...
zwithanx                           0.0  ...                   0.0
zxcsdfd                            0.0  ...                   0.0
zxjki                              0.0  ...                   0.0
zzdiane                            0.0  ...                   0.0
zzz1127                            0.0  ...                   0.0

[17891 rows x 255 columns]

#### Exporting the mapping file

In [289]:
mapping.to_pickle("prod_id_name_mapping.pkl")
pickled_mapping = pd.read_pickle("prod_id_name_mapping.pkl")
pickled_mapping

id                                               name
0      AV13O1A8GV-KLJ3akUyj          Pink Friday: Roman Reloaded Re-Up (w/dvd)
1      AV14LG0R-jtxr-f38QfS         Lundberg Organic Cinnamon Toast Rice Cakes
3      AV16khLE-jtxr-f38VFn                   K-Y Love Sensuality Pleasure Gel
30     AV1d76w7vKc47QAVhCqn               J.R. Watkins Hand Cream, Lemon Cream
36     AV1h6gSl-jtxr-f31p40                      Ambi Complexion Cleansing Bar
...                     ...                                                ...
28769  AVpfv4TlilAPnD_xhjNS  Various - Red Hot Blue:Tribute To Cole Porter ...
28772  AVpfvieo1cnluZ0-qdnu  L'oreal Paris Advanced Hairstyle TXT IT Hyper-...
28795  AVpfVMhR1cnluZ0-ixY8  2017-2018 Brownline174 Duraflex 14-Month Plann...
28799  AVpfVPh3ilAPnD_xZzW9           Mrs. Meyer's Lemon Verbena Surface Scrub
28814  AVpfW8y_LJeJML437ySW  L'or233al Paris Elvive Extraordinary Clay Reba...

[271 rows x 2 columns]